### ISSUE TITLE
Fix Prettier task

### ISSUE THREAD

**Issue by beefchimi** [beefchimi/threads#18]
Currently, running the `prettier` task results in a bunch of these:

```
prettier-stylelint [ERROR]: There was an error formatting "./properties/_z-index.scss"

TypeError: Cannot set property 'singleQuote' of null
    at resolveConfig.resolve (/Users/beefchimi/Development/Personal/threads/node_modules/prettier-stylelint/src/index.js:48:41)
    at linterAPI.getConfigForFile.then (/Users/beefchimi/Development/Personal/threads/node_modules/prettier-stylelint/src/index.js:32:31)
    at <anonymous>
```

Formatting the document within VSCode seems to work though. Not sure what the issue is. Introduced here: https://github.com/beefchimi/threads/pull/17

**Comment by ismail-syed** [comment]
Add a prettier config in package.json:

```
"prettier": {
  "singleQuote": true,
  "trailingComma": "es5",
  "bracketSpacing": false
}
```

as per the [docs] in `stylelint-config-shopify`.
